package com.alquimia.koua.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "KOUA_RECORD".
 */
public class KouaRecord {

    private Long id;
    /** Not-null value. */
    private String operation;
    private int operationType;
    private Double amount;
    private Integer authorization;
    private String message;
    private String date;

    public KouaRecord() {
    }

    public KouaRecord(Long id) {
        this.id = id;
    }

    public KouaRecord(Long id, String operation, int operationType, Double amount, Integer authorization, String message, String date) {
        this.id = id;
        this.operation = operation;
        this.operationType = operationType;
        this.amount = amount;
        this.authorization = authorization;
        this.message = message;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getOperation() {
        return operation;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOperation(String operation) {
        this.operation = operation;
    }

    public int getOperationType() {
        return operationType;
    }

    public void setOperationType(int operationType) {
        this.operationType = operationType;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public Integer getAuthorization() {
        return authorization;
    }

    public void setAuthorization(Integer authorization) {
        this.authorization = authorization;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

}
